/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Excel workbook for reading and writing .xlsx files. */
export declare class Workbook {
  /** Create a new empty workbook with a single sheet named "Sheet1". */
  constructor()
  /** Open an existing .xlsx file from disk. */
  static open(path: string): Workbook
  /** Save the workbook to a .xlsx file. */
  save(path: string): void
  /** Get the names of all sheets in workbook order. */
  get sheetNames(): Array<string>
}
