/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Forward-only streaming writer for large sheets. */
export declare class JsStreamWriter {
  /** Get the sheet name. */
  get sheetName(): string
  /** Set column width (1-based column number). */
  setColWidth(col: number, width: number): void
  /** Set column width for a range of columns. */
  setColWidthRange(minCol: number, maxCol: number, width: number): void
  /** Write a row of values. Rows must be written in ascending order. */
  writeRow(row: number, values: Array<string | number | boolean | null>): void
  /** Add a merge cell reference (e.g., "A1:C3"). */
  addMergeCell(reference: string): void
}

/** Excel workbook for reading and writing .xlsx files. */
export declare class Workbook {
  /** Create a new empty workbook with a single sheet named "Sheet1". */
  constructor()
  /** Open an existing .xlsx file from disk. */
  static openSync(path: string): Workbook
  /** Open an existing .xlsx file from disk asynchronously. */
  static open(path: string): Promise<Workbook>
  /** Save the workbook to a .xlsx file. */
  saveSync(path: string): void
  /** Save the workbook to a .xlsx file asynchronously. */
  save(path: string): Promise<void>
  /** Get the names of all sheets in workbook order. */
  get sheetNames(): Array<string>
  /** Get the value of a cell. Returns string, number, boolean, DateValue, or null. */
  getCellValue(sheet: string, cell: string): null | boolean | number | string | DateValue
  /** Set the value of a cell. Pass string, number, boolean, DateValue, or null to clear. */
  setCellValue(sheet: string, cell: string, value: string | number | boolean | DateValue | null): void
  /** Create a new empty sheet. Returns the 0-based sheet index. */
  newSheet(name: string): number
  /** Delete a sheet by name. */
  deleteSheet(name: string): void
  /** Rename a sheet. */
  setSheetName(oldName: string, newName: string): void
  /** Copy a sheet. Returns the new sheet's 0-based index. */
  copySheet(source: string, target: string): number
  /** Get the 0-based index of a sheet, or null if not found. */
  getSheetIndex(name: string): number | null
  /** Get the name of the active sheet. */
  getActiveSheet(): string
  /** Set the active sheet by name. */
  setActiveSheet(name: string): void
  /** Insert empty rows starting at the given 1-based row number. */
  insertRows(sheet: string, startRow: number, count: number): void
  /** Remove a row (1-based). */
  removeRow(sheet: string, row: number): void
  /** Duplicate a row (1-based). */
  duplicateRow(sheet: string, row: number): void
  /** Set the height of a row (1-based). */
  setRowHeight(sheet: string, row: number, height: number): void
  /** Get the height of a row, or null if not explicitly set. */
  getRowHeight(sheet: string, row: number): number | null
  /** Set whether a row is visible. */
  setRowVisible(sheet: string, row: number, visible: boolean): void
  /** Get whether a row is visible. Returns true if visible (not hidden). */
  getRowVisible(sheet: string, row: number): boolean
  /** Set the outline level of a row (0-7). */
  setRowOutlineLevel(sheet: string, row: number, level: number): void
  /** Get the outline level of a row. Returns 0 if not set. */
  getRowOutlineLevel(sheet: string, row: number): number
  /** Set the width of a column (e.g., "A", "B", "AA"). */
  setColWidth(sheet: string, col: string, width: number): void
  /** Get the width of a column, or null if not explicitly set. */
  getColWidth(sheet: string, col: string): number | null
  /** Set whether a column is visible. */
  setColVisible(sheet: string, col: string, visible: boolean): void
  /** Get whether a column is visible. Returns true if visible (not hidden). */
  getColVisible(sheet: string, col: string): boolean
  /** Set the outline level of a column (0-7). */
  setColOutlineLevel(sheet: string, col: string, level: number): void
  /** Get the outline level of a column. Returns 0 if not set. */
  getColOutlineLevel(sheet: string, col: string): number
  /** Insert empty columns starting at the given column letter. */
  insertCols(sheet: string, col: string, count: number): void
  /** Remove a column by letter. */
  removeCol(sheet: string, col: string): void
  /** Add a style definition. Returns the style ID for use with setCellStyle. */
  addStyle(style: JsStyle): number
  /** Get the style ID applied to a cell, or null if default. */
  getCellStyle(sheet: string, cell: string): number | null
  /** Apply a style ID to a cell. */
  setCellStyle(sheet: string, cell: string, styleId: number): void
  /** Apply a style ID to an entire row. */
  setRowStyle(sheet: string, row: number, styleId: number): void
  /** Get the style ID for a row. Returns 0 if not set. */
  getRowStyle(sheet: string, row: number): number
  /** Apply a style ID to an entire column. */
  setColStyle(sheet: string, col: string, styleId: number): void
  /** Get the style ID for a column. Returns 0 if not set. */
  getColStyle(sheet: string, col: string): number
  /** Add a chart to a sheet. */
  addChart(sheet: string, fromCell: string, toCell: string, config: JsChartConfig): void
  /** Add an image to a sheet. */
  addImage(sheet: string, config: JsImageConfig): void
  /** Merge a range of cells on a sheet. */
  mergeCells(sheet: string, topLeft: string, bottomRight: string): void
  /** Remove a merged cell range from a sheet. */
  unmergeCell(sheet: string, reference: string): void
  /** Get all merged cell ranges on a sheet. */
  getMergeCells(sheet: string): Array<string>
  /** Add a data validation rule to a sheet. */
  addDataValidation(sheet: string, config: JsDataValidationConfig): void
  /** Get all data validations on a sheet. */
  getDataValidations(sheet: string): Array<JsDataValidationConfig>
  /** Remove a data validation by sqref. */
  removeDataValidation(sheet: string, sqref: string): void
  /** Set conditional formatting rules on a cell range. */
  setConditionalFormat(sheet: string, sqref: string, rules: Array<JsConditionalFormatRule>): void
  /** Get all conditional formatting rules for a sheet. */
  getConditionalFormats(sheet: string): Array<JsConditionalFormatEntry>
  /** Delete conditional formatting for a specific cell range. */
  deleteConditionalFormat(sheet: string, sqref: string): void
  /** Add a comment to a cell. */
  addComment(sheet: string, config: JsCommentConfig): void
  /** Get all comments on a sheet. */
  getComments(sheet: string): Array<JsCommentConfig>
  /** Remove a comment from a cell. */
  removeComment(sheet: string, cell: string): void
  /** Set an auto-filter on a sheet. */
  setAutoFilter(sheet: string, range: string): void
  /** Remove the auto-filter from a sheet. */
  removeAutoFilter(sheet: string): void
  /** Create a new stream writer for a new sheet. */
  newStreamWriter(sheetName: string): JsStreamWriter
  /** Apply a stream writer's output to the workbook. Returns the sheet index. */
  applyStreamWriter(writer: JsStreamWriter): number
  /** Set core document properties (title, creator, etc.). */
  setDocProps(props: JsDocProperties): void
  /** Get core document properties. */
  getDocProps(): JsDocProperties
  /** Set application properties (company, app version, etc.). */
  setAppProps(props: JsAppProperties): void
  /** Get application properties. */
  getAppProps(): JsAppProperties
  /** Set a custom property. Value can be string, number, or boolean. */
  setCustomProperty(name: string, value: string | number | boolean): void
  /** Get a custom property value, or null if not found. */
  getCustomProperty(name: string): string | number | boolean | null
  /** Delete a custom property. Returns true if it existed. */
  deleteCustomProperty(name: string): boolean
  /** Protect the workbook structure/windows with optional password. */
  protectWorkbook(config: JsWorkbookProtectionConfig): void
  /** Remove workbook protection. */
  unprotectWorkbook(): void
  /** Check if the workbook is protected. */
  isWorkbookProtected(): boolean
  /**
   * Set freeze panes on a sheet.
   * The cell reference indicates the top-left cell of the scrollable area.
   * For example, "A2" freezes row 1, "B1" freezes column A.
   */
  setPanes(sheet: string, cell: string): void
  /** Remove any freeze or split panes from a sheet. */
  unsetPanes(sheet: string): void
  /** Get the current freeze pane cell reference for a sheet, or null if none. */
  getPanes(sheet: string): string | null
  /** Set page margins on a sheet (values in inches). */
  setPageMargins(sheet: string, margins: JsPageMargins): void
  /** Get page margins for a sheet. Returns defaults if not explicitly set. */
  getPageMargins(sheet: string): JsPageMargins
  /** Set page setup options (paper size, orientation, scale, fit-to-page). */
  setPageSetup(sheet: string, setup: JsPageSetup): void
  /** Get the page setup for a sheet. */
  getPageSetup(sheet: string): JsPageSetup
  /** Set header and footer text for printing. */
  setHeaderFooter(sheet: string, header?: string | undefined | null, footer?: string | undefined | null): void
  /**
   * Get the header and footer text for a sheet.
   * Returns an object with `header` and `footer` fields, each possibly null.
   */
  getHeaderFooter(sheet: string): JsHeaderFooter
  /** Set print options on a sheet. */
  setPrintOptions(sheet: string, opts: JsPrintOptions): void
  /** Get print options for a sheet. */
  getPrintOptions(sheet: string): JsPrintOptions
  /** Insert a horizontal page break before the given 1-based row. */
  insertPageBreak(sheet: string, row: number): void
  /** Remove a horizontal page break at the given 1-based row. */
  removePageBreak(sheet: string, row: number): void
  /** Get all row page break positions (1-based row numbers). */
  getPageBreaks(sheet: string): Array<number>
  /** Set a hyperlink on a cell. */
  setCellHyperlink(sheet: string, cell: string, opts: JsHyperlinkOptions): void
  /** Get hyperlink information for a cell, or null if no hyperlink exists. */
  getCellHyperlink(sheet: string, cell: string): JsHyperlinkInfo | null
  /** Delete a hyperlink from a cell. */
  deleteCellHyperlink(sheet: string, cell: string): void
  /**
   * Get all rows with their data from a sheet.
   * Only rows that contain at least one cell are included.
   */
  getRows(sheet: string): Array<JsRowData>
  /**
   * Get all columns with their data from a sheet.
   * Only columns that have data are included.
   */
  getCols(sheet: string): Array<JsColData>
  /** Evaluate a formula string against the current workbook data. */
  evaluateFormula(sheet: string, formula: string): null | boolean | number | string | DateValue
  /** Recalculate all formula cells in the workbook. */
  calculateAll(): void
  /** Add a pivot table to the workbook. */
  addPivotTable(config: JsPivotTableConfig): void
  /** Get all pivot tables in the workbook. */
  getPivotTables(): Array<JsPivotTableInfo>
  /** Delete a pivot table by name. */
  deletePivotTable(name: string): void
  /** Add a sparkline to a worksheet. */
  addSparkline(sheet: string, config: JsSparklineConfig): void
  /** Get all sparklines for a worksheet. */
  getSparklines(sheet: string): Array<JsSparklineConfig>
  /** Remove a sparkline by its location cell reference. */
  removeSparkline(sheet: string, location: string): void
  /** Set a cell to a rich text value with multiple formatted runs. */
  setCellRichText(sheet: string, cell: string, runs: Array<JsRichTextRun>): void
  /** Get rich text runs for a cell, or null if not rich text. */
  getCellRichText(sheet: string, cell: string): Array<JsRichTextRun> | null
  /**
   * Resolve a theme color by index (0-11) with optional tint.
   * Returns the ARGB hex string (e.g. "FF4472C4") or null if out of range.
   */
  getThemeColor(index: number, tint?: number | undefined | null): string | null
  /**
   * Add or update a defined name. If a name with the same name and scope
   * already exists, its value and comment are updated.
   */
  setDefinedName(config: JsDefinedNameConfig): void
  /**
   * Get a defined name by name and optional scope (sheet name).
   * Returns null if no matching defined name is found.
   */
  getDefinedName(name: string, scope?: string | undefined | null): JsDefinedNameInfo | null
  /** Get all defined names in the workbook. */
  getDefinedNames(): Array<JsDefinedNameInfo>
  /** Delete a defined name by name and optional scope (sheet name). */
  deleteDefinedName(name: string, scope?: string | undefined | null): void
  /** Protect a sheet with optional password and permission settings. */
  protectSheet(sheet: string, config?: JsSheetProtectionConfig | undefined | null): void
  /** Remove sheet protection. */
  unprotectSheet(sheet: string): void
  /** Check if a sheet is protected. */
  isSheetProtected(sheet: string): boolean
}

export interface DateValue {
  type: string
  serial: number
  iso?: string
}

export interface JsAlignmentStyle {
  horizontal?: string
  vertical?: string
  wrapText?: boolean
  textRotation?: number
  indent?: number
  shrinkToFit?: boolean
}

export interface JsAppProperties {
  application?: string
  docSecurity?: number
  company?: string
  appVersion?: string
  manager?: string
  template?: string
}

export interface JsBorderSideStyle {
  style?: string
  color?: string
}

export interface JsBorderStyle {
  left?: JsBorderSideStyle
  right?: JsBorderSideStyle
  top?: JsBorderSideStyle
  bottom?: JsBorderSideStyle
  diagonal?: JsBorderSideStyle
}

export interface JsChartConfig {
  chartType: string
  title?: string
  series: Array<JsChartSeries>
  showLegend?: boolean
  view3D?: JsView3DConfig
}

export interface JsChartSeries {
  name: string
  categories: string
  values: string
  xValues?: string
  bubbleSizes?: string
}

/** A single cell entry with its row number and value. */
export interface JsColCell {
  /** 1-based row number. */
  row: number
  /** Cell value type: "string", "number", "boolean", "date", "empty", "error", "formula". */
  valueType: string
  /** String representation of the cell value. */
  value?: string
  /** Numeric value (only set when value_type is "number"). */
  numberValue?: number
  /** Boolean value (only set when value_type is "boolean"). */
  boolValue?: boolean
}

/** A column with its name and cell data. */
export interface JsColData {
  /** Column name (e.g., "A", "B", "AA"). */
  column: string
  /** Cells with data in this column. */
  cells: Array<JsColCell>
}

export interface JsCommentConfig {
  cell: string
  author: string
  text: string
}

/** Result of getting conditional formats from a sheet. */
export interface JsConditionalFormatEntry {
  /** Cell range (e.g., "A1:A100"). */
  sqref: string
  /** Rules applied to this range. */
  rules: Array<JsConditionalFormatRule>
}

/** Conditional formatting rule configuration. */
export interface JsConditionalFormatRule {
  /**
   * Rule type: "cellIs", "expression", "colorScale", "dataBar",
   * "duplicateValues", "uniqueValues", "top10", "bottom10",
   * "aboveAverage", "containsBlanks", "notContainsBlanks",
   * "containsErrors", "notContainsErrors", "containsText",
   * "notContainsText", "beginsWith", "endsWith".
   */
  ruleType: string
  /** Comparison operator for cellIs rules. */
  operator?: string
  /** First formula/value. */
  formula?: string
  /** Second formula/value (for between/notBetween). */
  formula2?: string
  /** Text for text-based rules. */
  text?: string
  /** Rank for top10/bottom10 rules. */
  rank?: number
  /** Whether rank is a percentage. */
  percent?: boolean
  /** Whether rule is above average (for aboveAverage rules). */
  above?: boolean
  /** Whether equal values count as matching (for aboveAverage rules). */
  equalAverage?: boolean
  /** Color scale minimum value type. */
  minType?: string
  /** Color scale minimum value. */
  minValue?: string
  /** Color scale minimum color (ARGB hex). */
  minColor?: string
  /** Color scale middle value type. */
  midType?: string
  /** Color scale middle value. */
  midValue?: string
  /** Color scale middle color (ARGB hex). */
  midColor?: string
  /** Color scale maximum value type. */
  maxType?: string
  /** Color scale maximum value. */
  maxValue?: string
  /** Color scale maximum color (ARGB hex). */
  maxColor?: string
  /** Data bar color (ARGB hex). */
  barColor?: string
  /** Whether to show the cell value alongside the data bar. */
  showValue?: boolean
  /** Differential style to apply. */
  format?: JsConditionalStyle
  /** Rule priority (lower = higher precedence). */
  priority?: number
  /** If true, no lower-priority rules apply when this matches. */
  stopIfTrue?: boolean
}

/** Conditional formatting style (differential format). */
export interface JsConditionalStyle {
  font?: JsFontStyle
  fill?: JsFillStyle
  border?: JsBorderStyle
  customNumFmt?: string
}

export interface JsDataValidationConfig {
  sqref: string
  validationType: string
  operator?: string
  formula1?: string
  formula2?: string
  allowBlank?: boolean
  errorStyle?: string
  errorTitle?: string
  errorMessage?: string
  promptTitle?: string
  promptMessage?: string
  showInputMessage?: boolean
  showErrorMessage?: boolean
}

/** Configuration for setting a defined name. */
export interface JsDefinedNameConfig {
  /** The name to define (e.g., "SalesData"). */
  name: string
  /** The reference or formula (e.g., "Sheet1!$A$1:$D$10"). */
  value: string
  /** Optional sheet name for sheet-scoped names. Omit for workbook scope. */
  scope?: string
  /** Optional comment for the defined name. */
  comment?: string
}

/** Information about a defined name returned by getDefinedName/getDefinedNames. */
export interface JsDefinedNameInfo {
  /** The defined name. */
  name: string
  /** The reference or formula. */
  value: string
  /** Sheet name if sheet-scoped, or null if workbook-scoped. */
  scope?: string
  /** Optional comment. */
  comment?: string
}

export interface JsDocProperties {
  title?: string
  subject?: string
  creator?: string
  keywords?: string
  description?: string
  lastModifiedBy?: string
  revision?: string
  created?: string
  modified?: string
  category?: string
  contentStatus?: string
}

export interface JsFillStyle {
  pattern?: string
  fgColor?: string
  bgColor?: string
}

export interface JsFontStyle {
  name?: string
  size?: number
  bold?: boolean
  italic?: boolean
  underline?: boolean
  strikethrough?: boolean
  color?: string
}

/** Header and footer text. */
export interface JsHeaderFooter {
  /** Header text (may use Excel formatting codes like &L, &C, &R). */
  header?: string
  /** Footer text (may use Excel formatting codes like &L, &C, &R). */
  footer?: string
}

export interface JsHyperlinkInfo {
  /** Type of hyperlink: "external", "internal", or "email". */
  linkType: string
  /** The target URL, sheet reference, or email address. */
  target: string
  /** Optional display text. */
  display?: string
  /** Optional tooltip text. */
  tooltip?: string
}

export interface JsHyperlinkOptions {
  /** Type of hyperlink: "external", "internal", or "email". */
  linkType: string
  /** The target URL, sheet reference, or email address. */
  target: string
  /** Optional display text. */
  display?: string
  /** Optional tooltip text. */
  tooltip?: string
}

export interface JsImageConfig {
  data: Buffer
  format: string
  fromCell: string
  widthPx: number
  heightPx: number
}

/** Page margins configuration in inches. */
export interface JsPageMargins {
  /** Left margin in inches (default 0.7). */
  left: number
  /** Right margin in inches (default 0.7). */
  right: number
  /** Top margin in inches (default 0.75). */
  top: number
  /** Bottom margin in inches (default 0.75). */
  bottom: number
  /** Header margin in inches (default 0.3). */
  header: number
  /** Footer margin in inches (default 0.3). */
  footer: number
}

/** Page setup configuration. */
export interface JsPageSetup {
  /** Paper size: "letter", "tabloid", "legal", "a3", "a4", "a5", "b4", "b5". */
  paperSize?: string
  /** Orientation: "portrait" or "landscape". */
  orientation?: string
  /** Print scale percentage (10-400). */
  scale?: number
  /** Fit to this many pages wide. */
  fitToWidth?: number
  /** Fit to this many pages tall. */
  fitToHeight?: number
}

export interface JsPivotDataField {
  name: string
  function: string
  displayName?: string
}

export interface JsPivotField {
  name: string
}

export interface JsPivotTableConfig {
  name: string
  sourceSheet: string
  sourceRange: string
  targetSheet: string
  targetCell: string
  rows: Array<JsPivotField>
  columns: Array<JsPivotField>
  data: Array<JsPivotDataField>
}

export interface JsPivotTableInfo {
  name: string
  sourceSheet: string
  sourceRange: string
  targetSheet: string
  location: string
}

/** Print options configuration. */
export interface JsPrintOptions {
  /** Print gridlines. */
  gridLines?: boolean
  /** Print row/column headings. */
  headings?: boolean
  /** Center horizontally on page. */
  horizontalCentered?: boolean
  /** Center vertically on page. */
  verticalCentered?: boolean
}

export interface JsProtectionStyle {
  locked?: boolean
  hidden?: boolean
}

/** A single formatted text segment within a rich text cell. */
export interface JsRichTextRun {
  text: string
  font?: string
  size?: number
  bold?: boolean
  italic?: boolean
  color?: string
}

/** A single cell entry with its column name and value. */
export interface JsRowCell {
  /** Column name (e.g., "A", "B", "AA"). */
  column: string
  /** Cell value type: "string", "number", "boolean", "date", "empty", "error", "formula". */
  valueType: string
  /** String representation of the cell value. */
  value?: string
  /** Numeric value (only set when value_type is "number"). */
  numberValue?: number
  /** Boolean value (only set when value_type is "boolean"). */
  boolValue?: boolean
}

/** A row with its 1-based row number and cell data. */
export interface JsRowData {
  /** 1-based row number. */
  row: number
  /** Cells with data in this row. */
  cells: Array<JsRowCell>
}

/** Configuration for sheet protection. */
export interface JsSheetProtectionConfig {
  /** Optional password (hashed with legacy Excel algorithm). */
  password?: string
  /** Allow selecting locked cells. */
  selectLockedCells?: boolean
  /** Allow selecting unlocked cells. */
  selectUnlockedCells?: boolean
  /** Allow formatting cells. */
  formatCells?: boolean
  /** Allow formatting columns. */
  formatColumns?: boolean
  /** Allow formatting rows. */
  formatRows?: boolean
  /** Allow inserting columns. */
  insertColumns?: boolean
  /** Allow inserting rows. */
  insertRows?: boolean
  /** Allow inserting hyperlinks. */
  insertHyperlinks?: boolean
  /** Allow deleting columns. */
  deleteColumns?: boolean
  /** Allow deleting rows. */
  deleteRows?: boolean
  /** Allow sorting. */
  sort?: boolean
  /** Allow using auto-filter. */
  autoFilter?: boolean
  /** Allow using pivot tables. */
  pivotTables?: boolean
}

export interface JsSparklineConfig {
  dataRange: string
  location: string
  sparklineType?: string
  markers?: boolean
  highPoint?: boolean
  lowPoint?: boolean
  firstPoint?: boolean
  lastPoint?: boolean
  negativePoints?: boolean
  showAxis?: boolean
  lineWeight?: number
  style?: number
}

export interface JsStyle {
  font?: JsFontStyle
  fill?: JsFillStyle
  border?: JsBorderStyle
  alignment?: JsAlignmentStyle
  numFmtId?: number
  customNumFmt?: string
  protection?: JsProtectionStyle
}

export interface JsView3DConfig {
  rotX?: number
  rotY?: number
  depthPercent?: number
  rightAngleAxes?: boolean
  perspective?: number
}

export interface JsWorkbookProtectionConfig {
  password?: string
  lockStructure?: boolean
  lockWindows?: boolean
  lockRevision?: boolean
}
