/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsFontStyle {
  name?: string
  size?: number
  bold?: boolean
  italic?: boolean
  underline?: boolean
  strikethrough?: boolean
  color?: string
}
export interface JsFillStyle {
  pattern?: string
  fgColor?: string
  bgColor?: string
}
export interface JsBorderSideStyle {
  style?: string
  color?: string
}
export interface JsBorderStyle {
  left?: JsBorderSideStyle
  right?: JsBorderSideStyle
  top?: JsBorderSideStyle
  bottom?: JsBorderSideStyle
  diagonal?: JsBorderSideStyle
}
export interface JsAlignmentStyle {
  horizontal?: string
  vertical?: string
  wrapText?: boolean
  textRotation?: number
  indent?: number
  shrinkToFit?: boolean
}
export interface JsProtectionStyle {
  locked?: boolean
  hidden?: boolean
}
export interface JsStyle {
  font?: JsFontStyle
  fill?: JsFillStyle
  border?: JsBorderStyle
  alignment?: JsAlignmentStyle
  numFmtId?: number
  customNumFmt?: string
  protection?: JsProtectionStyle
}
export interface JsChartSeries {
  name: string
  categories: string
  values: string
}
export interface JsChartConfig {
  chartType: string
  title?: string
  series: Array<JsChartSeries>
  showLegend?: boolean
}
export interface JsImageConfig {
  data: Buffer
  format: string
  fromCell: string
  widthPx: number
  heightPx: number
}
export interface JsCommentConfig {
  cell: string
  author: string
  text: string
}
export interface JsDataValidationConfig {
  sqref: string
  validationType: string
  operator?: string
  formula1?: string
  formula2?: string
  allowBlank?: boolean
  errorStyle?: string
  errorTitle?: string
  errorMessage?: string
  promptTitle?: string
  promptMessage?: string
  showInputMessage?: boolean
  showErrorMessage?: boolean
}
export interface JsDocProperties {
  title?: string
  subject?: string
  creator?: string
  keywords?: string
  description?: string
  lastModifiedBy?: string
  revision?: string
  created?: string
  modified?: string
  category?: string
  contentStatus?: string
}
export interface JsAppProperties {
  application?: string
  docSecurity?: number
  company?: string
  appVersion?: string
  manager?: string
  template?: string
}
export interface JsWorkbookProtectionConfig {
  password?: string
  lockStructure?: boolean
  lockWindows?: boolean
  lockRevision?: boolean
}
export interface JsHyperlinkOptions {
  /** Type of hyperlink: "external", "internal", or "email". */
  linkType: string
  /** The target URL, sheet reference, or email address. */
  target: string
  /** Optional display text. */
  display?: string
  /** Optional tooltip text. */
  tooltip?: string
}
export interface JsHyperlinkInfo {
  /** Type of hyperlink: "external", "internal", or "email". */
  linkType: string
  /** The target URL, sheet reference, or email address. */
  target: string
  /** Optional display text. */
  display?: string
  /** Optional tooltip text. */
  tooltip?: string
}
/** A single cell entry with its column name and value. */
export interface JsRowCell {
  /** Column name (e.g., "A", "B", "AA"). */
  column: string
  /** Cell value type: "string", "number", "boolean", "date", "empty", "error", "formula". */
  valueType: string
  /** String representation of the cell value. */
  value?: string
  /** Numeric value (only set when value_type is "number"). */
  numberValue?: number
  /** Boolean value (only set when value_type is "boolean"). */
  boolValue?: boolean
}
/** A row with its 1-based row number and cell data. */
export interface JsRowData {
  /** 1-based row number. */
  row: number
  /** Cells with data in this row. */
  cells: Array<JsRowCell>
}
/** A single cell entry with its row number and value. */
export interface JsColCell {
  /** 1-based row number. */
  row: number
  /** Cell value type: "string", "number", "boolean", "date", "empty", "error", "formula". */
  valueType: string
  /** String representation of the cell value. */
  value?: string
  /** Numeric value (only set when value_type is "number"). */
  numberValue?: number
  /** Boolean value (only set when value_type is "boolean"). */
  boolValue?: boolean
}
/** A column with its name and cell data. */
export interface JsColData {
  /** Column name (e.g., "A", "B", "AA"). */
  column: string
  /** Cells with data in this column. */
  cells: Array<JsColCell>
}
/** Excel workbook for reading and writing .xlsx files. */
export declare class Workbook {
  /** Create a new empty workbook with a single sheet named "Sheet1". */
  constructor()
  /** Open an existing .xlsx file from disk. */
  static open(path: string): Workbook
  /** Save the workbook to a .xlsx file. */
  save(path: string): void
  /** Get the names of all sheets in workbook order. */
  get sheetNames(): Array<string>
  /** Get the value of a cell. Returns string, number, boolean, DateValue, or null. */
  getCellValue(sheet: string, cell: string): string | number | boolean | DateValue | null
  /** Set the value of a cell. Pass string, number, boolean, DateValue, or null to clear. */
  setCellValue(sheet: string, cell: string, value: string | number | boolean | { type: 'date', serial: number } | null): void
  /** Create a new empty sheet. Returns the 0-based sheet index. */
  newSheet(name: string): number
  /** Delete a sheet by name. */
  deleteSheet(name: string): void
  /** Rename a sheet. */
  setSheetName(oldName: string, newName: string): void
  /** Copy a sheet. Returns the new sheet's 0-based index. */
  copySheet(source: string, target: string): number
  /** Get the 0-based index of a sheet, or null if not found. */
  getSheetIndex(name: string): number | null
  /** Get the name of the active sheet. */
  getActiveSheet(): string
  /** Set the active sheet by name. */
  setActiveSheet(name: string): void
  /** Insert empty rows starting at the given 1-based row number. */
  insertRows(sheet: string, startRow: number, count: number): void
  /** Remove a row (1-based). */
  removeRow(sheet: string, row: number): void
  /** Duplicate a row (1-based). */
  duplicateRow(sheet: string, row: number): void
  /** Set the height of a row (1-based). */
  setRowHeight(sheet: string, row: number, height: number): void
  /** Get the height of a row, or null if not explicitly set. */
  getRowHeight(sheet: string, row: number): number | null
  /** Set whether a row is visible. */
  setRowVisible(sheet: string, row: number, visible: boolean): void
  /** Get whether a row is visible. Returns true if visible (not hidden). */
  getRowVisible(sheet: string, row: number): boolean
  /** Set the outline level of a row (0-7). */
  setRowOutlineLevel(sheet: string, row: number, level: number): void
  /** Get the outline level of a row. Returns 0 if not set. */
  getRowOutlineLevel(sheet: string, row: number): number
  /** Set the width of a column (e.g., "A", "B", "AA"). */
  setColWidth(sheet: string, col: string, width: number): void
  /** Get the width of a column, or null if not explicitly set. */
  getColWidth(sheet: string, col: string): number | null
  /** Set whether a column is visible. */
  setColVisible(sheet: string, col: string, visible: boolean): void
  /** Get whether a column is visible. Returns true if visible (not hidden). */
  getColVisible(sheet: string, col: string): boolean
  /** Set the outline level of a column (0-7). */
  setColOutlineLevel(sheet: string, col: string, level: number): void
  /** Get the outline level of a column. Returns 0 if not set. */
  getColOutlineLevel(sheet: string, col: string): number
  /** Insert empty columns starting at the given column letter. */
  insertCols(sheet: string, col: string, count: number): void
  /** Remove a column by letter. */
  removeCol(sheet: string, col: string): void
  /** Add a style definition. Returns the style ID for use with setCellStyle. */
  addStyle(style: JsStyle): number
  /** Get the style ID applied to a cell, or null if default. */
  getCellStyle(sheet: string, cell: string): number | null
  /** Apply a style ID to a cell. */
  setCellStyle(sheet: string, cell: string, styleId: number): void
  /** Add a chart to a sheet. */
  addChart(sheet: string, fromCell: string, toCell: string, config: JsChartConfig): void
  /** Add an image to a sheet. */
  addImage(sheet: string, config: JsImageConfig): void
  /** Merge a range of cells on a sheet. */
  mergeCells(sheet: string, topLeft: string, bottomRight: string): void
  /** Remove a merged cell range from a sheet. */
  unmergeCell(sheet: string, reference: string): void
  /** Get all merged cell ranges on a sheet. */
  getMergeCells(sheet: string): Array<string>
  /** Add a data validation rule to a sheet. */
  addDataValidation(sheet: string, config: JsDataValidationConfig): void
  /** Get all data validations on a sheet. */
  getDataValidations(sheet: string): Array<JsDataValidationConfig>
  /** Remove a data validation by sqref. */
  removeDataValidation(sheet: string, sqref: string): void
  /** Add a comment to a cell. */
  addComment(sheet: string, config: JsCommentConfig): void
  /** Get all comments on a sheet. */
  getComments(sheet: string): Array<JsCommentConfig>
  /** Remove a comment from a cell. */
  removeComment(sheet: string, cell: string): void
  /** Set an auto-filter on a sheet. */
  setAutoFilter(sheet: string, range: string): void
  /** Remove the auto-filter from a sheet. */
  removeAutoFilter(sheet: string): void
  /** Create a new stream writer for a new sheet. */
  newStreamWriter(sheetName: string): JsStreamWriter
  /** Apply a stream writer's output to the workbook. Returns the sheet index. */
  applyStreamWriter(writer: JsStreamWriter): number
  /** Set core document properties (title, creator, etc.). */
  setDocProps(props: JsDocProperties): void
  /** Get core document properties. */
  getDocProps(): JsDocProperties
  /** Set application properties (company, app version, etc.). */
  setAppProps(props: JsAppProperties): void
  /** Get application properties. */
  getAppProps(): JsAppProperties
  /** Set a custom property. Value can be string, number, or boolean. */
  setCustomProperty(name: string, value: string | number | boolean): void
  /** Get a custom property value, or null if not found. */
  getCustomProperty(name: string): string | number | boolean | null
  /** Delete a custom property. Returns true if it existed. */
  deleteCustomProperty(name: string): boolean
  /** Protect the workbook structure/windows with optional password. */
  protectWorkbook(config: JsWorkbookProtectionConfig): void
  /** Remove workbook protection. */
  unprotectWorkbook(): void
  /** Check if the workbook is protected. */
  isWorkbookProtected(): boolean
  /**
   * Set freeze panes on a sheet.
   * The cell reference indicates the top-left cell of the scrollable area.
   * For example, "A2" freezes row 1, "B1" freezes column A.
   */
  setPanes(sheet: string, cell: string): void
  /** Remove any freeze or split panes from a sheet. */
  unsetPanes(sheet: string): void
  /** Get the current freeze pane cell reference for a sheet, or null if none. */
  getPanes(sheet: string): string | null
  /** Set a hyperlink on a cell. */
  setCellHyperlink(sheet: string, cell: string, opts: JsHyperlinkOptions): void
  /** Get hyperlink information for a cell, or null if no hyperlink exists. */
  getCellHyperlink(sheet: string, cell: string): JsHyperlinkInfo | null
  /** Delete a hyperlink from a cell. */
  deleteCellHyperlink(sheet: string, cell: string): void
  /**
   * Get all rows with their data from a sheet.
   * Only rows that contain at least one cell are included.
   */
  getRows(sheet: string): Array<JsRowData>
  /**
   * Get all columns with their data from a sheet.
   * Only columns that have data are included.
   */
  getCols(sheet: string): Array<JsColData>
}
/** Forward-only streaming writer for large sheets. */
export declare class JsStreamWriter {
  /** Get the sheet name. */
  get sheetName(): string
  /** Set column width (1-based column number). */
  setColWidth(col: number, width: number): void
  /** Set column width for a range of columns. */
  setColWidthRange(minCol: number, maxCol: number, width: number): void
  /** Write a row of values. Rows must be written in ascending order. */
  writeRow(row: number, values: Array<string | number | boolean | null>): void
  /** Add a merge cell reference (e.g., "A1:C3"). */
  addMergeCell(reference: string): void
}
